objects/Test1__c.object
<CustomObject>
    <fields>
        <fullName>Approved__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Approved</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>GB</fullName>
                </value>
                <value>
                    <fullName>EU</fullName>
                </value>
                <value>
                    <fullName>PL</fullName>
                </value>
                <value>
                    <fullName>HU</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Test1</label>
    <nameField>
        <label>Test1 Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Test1</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/Test1TRGTest.cls
@istest
public class Test1TRGTest {
    
    @isTest static void Test1Test()
    {
    	Test1__c a = New Test1__c();
        a.Approved__c = true;
    	a.Country__c ='PL';
    
    	insert a;
    
   		List<Test1__c> b = New List<Test1__c>([select id,Country__c from Test1__c where id =: a.id]);
    	System.assertEquals('PL', b[0].Country__c,'Sorry Country does not Match');
    }
    
        
    

}