objects/zConference__c.object
<CustomObject>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>10</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Qty__c</fullName>
        <label>Qty</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Rate__c</fullName>
        <label>Rate</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>zConference</label>
    <nameField>
        <label>zConference Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>zConference</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/zConfTrgHandller.cls
/**
 * @author moc <moc@polsource.com>
 * Comment line 2
 */
public class zConfTrgHandller {
    private static void zConfTrgHandller()
    {
        //MyPrivate Constructor
    }
    //This method will calculate the price 
    //base on Product, Qty and Rate
    public static void calcPrice(List<zConference__c> lstofzc){
         for(zConference__c a : lstofzc) {
         	a.price__c = a.qty__c * a.rate__c;
    	}
    }

}